### ISSUE TITLE
Bug lors du téléchargement de l’ensemble des attestations des stagiaires 

### ISSUE THREAD

**Issue by jonathanjoegit** [cemu-guillaumegirard/attestoodle#7]
(voir screenshot)
![screen shot 2018-05-22 at 16 01 59](https://user-images.githubusercontent.com/12695763/40414801-8c9c60aa-5e79-11e8-9bed-94024cc0de3e.png)

**Comment by cemu-guillaumegirard** [comment]
Some activities doesn't have an "intro" field in their DB table. The factory didn't check this eventuality when retrieve DB data and create the activities, therefore pointing to a undefined value. Added this check.

Corrected on branch bugfix (**commit d86f766**)
